### ISSUE TITLE
mysql problem acl SUB/PUB

### ISSUE THREAD

**Issue by ElizabethMorves** [jpmens/mosquitto-auth-plug#395] opened 2019-01-24 04:27 UTC
I ran into an undocumented problem
this string
`auth_opt_aclquery SELECT topic FROM mqtt_acls WHERE ( username = '%s' ) AND ( rw >= %d)`

mysql general_log =on
restore this
`tail  -f  /var/log/mysql/mysql.log  | grep "SELECT topic FROM mqtt"    \n
2019-01-24T03:57:57.380843Z	   76 Query	SELECT topic FROM mqtt_acls WHERE username = 'Uzh0r' AND rw >= 4`

What? Why here 4? What does 4 here? how can i repair ACL SUB/PUB?
sorry if this was already discussed somewhere.
could not find the answer. 

eclipse-mosquitto v1.5.5
mqtt-spy 1.0.0 (build 3)
thank

upd:
4 = permission subscribe to topic or something like that. It slips when I try to subscribe to a topic. But I can still post to the topic with database rw = 2. Hmmm ... What am I doing wrong? 
```

1548312610: Sending CONNACK to SSL_MQTT_Uzh0r (0, 0)
1548312610: Received SUBSCRIBE from SSL_MQTT_Uzh0r
1548312610: 	/konbanwa (QoS 0)
1548312610: |-- mosquitto_auth_acl_check(..., client id not available, Uzh0r, /konbanwa, MOSQ_ACL_WRITE)
1548312610: |-- SQL: SELECT topic FROM mqtt_acls WHERE username = 'Uzh0r' AND rw = 4
1548312610: |-- aclcheck(Uzh0r, /konbanwa, 4) AUTHORIZED=0 by none
1548312610: |--  Cached  [07199A68645340B76DD9C1118B58DC905D41E38D] for (client id not available,Uzh0r,4)
1548312610: Sending SUBACK to SSL_MQTT_Uzh0r
```

**Comment by jpmens** [comment] 2019-01-24 07:15
Duplicate of #356

**Closed by jpmens** 2019-01-24 07:15 UTC

**Comment by ElizabethMorves** [comment] 2019-01-24 08:35
Wow, Thanks for attention. very helpfu.
