### ISSUE TITLE
Mosquitto JWT authentication

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#225] opened 2017-03-27 14:11 UTC
Hello,
Firstly i want to say thanks about this plugin.
I want to implement JWT authentication. How i can build server for authenticated JWT like example for http ?
Thank's for advance

**Comment by jpmens** [comment] 2017-03-27 17:16
Duplicate of #220

**Closed by jpmens** 2017-03-27 17:16 UTC
