### ISSUE TITLE
libwebsockets assertion "insert_wsi" fails whith http and jwt back-end

### ISSUE THREAD

**Issue by martindederer** [jpmens/mosquitto-auth-plug#283] opened 2017-07-25 13:42 UTC
I am trying to authenticate MQTT clients with the http (respectively jwt) back-end.

I am using mosquitto 1.4.14-0mosquitto1~xenial1 and mosquitto-auth-plugin 0.0.7-2build1 from the ubuntu 16.04 repositories. I am using the http-auth-be.py ptyhon server script from the examples as auth-server.

This is my mosquitto.conf:

```
# tcp
listener 9000

# websocket
listener 9001
protocol websockets

# common
allow_anonymous false
log_type all

# auth
auth_plugin /usr/lib/mosquitto-auth-plugin/auth-plugin.so
auth_opt_backends http
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 8100
#auth_opt_http_hostname example.org
auth_opt_http_getuser_uri /auth
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl
```

Whenever i try to connect to the MQTT broker with a non-empty username it bails out with the following assertion.

```
1500988888: mosquitto version 1.4.14 (build date Tue, 11 Jul 2017 00:29:26 +0100) starting
1500988888: Config loaded from ./mosquitto.conf.
1500988888: |-- *** auth-plug: startup
1500988888: |-- ** Configured order: jwt

1500988888: |-- with_tls=false
1500988888: |-- getuser_uri=/auth
1500988888: |-- superuser_uri=/superuser
1500988888: |-- aclcheck_uri=/acl
1500988888: |-- getuser_params=(null)
1500988888: |-- superuser_params=(null)
1500988888: |-- aclcheck_paramsi=(null)
1500988888: Opening ipv4 listen socket on port 9000.
1500988888: Opening ipv6 listen socket on port 9000.
1500988888: Opening websockets listen socket on port 9001.
1500988898: Sending CONNACK to 127.0.0.1 (0, 5)
mosquitto: /build/libwebsockets-WwGyDW/libwebsockets-1.7.1/lib/pollfd.c:138: insert_wsi_socket_into_fds: Assertion `context->lws_lookup[wsi->sock] == 0' failed.
```

As far as i can tell from the log output of the auth server it does not receive a http request from the MQTT broker.

Did i miss something important? Apparently the assertion emanates from libwebsockets. Is this caused by mosquitto, mosquitto-auth-plug or libwebsockets?

**Comment by chenjiancan** [comment] 2017-07-28 13:26
get same crash with mysql backend

**Comment by MohamedAbdallah-14** [comment] 2017-08-01 14:55
have the same problem here 

1501599295: Sending CONNACK to 192.168.1.2 (0, 5)
mosquitto: /build/libwebsockets-9s1kHy/libwebsockets-1.7.1/lib/pollfd.c:138: insert_wsi_socket_into_fds: Assertion `context->lws_lookup[wsi->sock] == 0' failed.
Aborted

**Comment by ramarro123** [comment] 2017-08-02 20:10
same problem for me
mosquitto: /build/libwebsockets-WwGyDW/libwebsockets-1.7.1/lib/pollfd.c:138: insert_wsi_socket_into_fds: Assertion `context->lws_lookup[wsi->sock] == 0' failed.

**Comment by jpmens** [comment] 2017-08-09 06:49
So, what's the verdict?

**Comment by Tryforce** [comment] 2017-09-26 18:01
I'm not sure if anyone else found a fix for this, but I am having the same problem as well. It's hard to tell where the problem is exactly, but it might be with mosquitto or libwebsockets.

**Comment by iegomez** [comment] 2017-10-24 15:13
Hi guys, I was having the same problem, and from what I could find it seemed that the culprit was libwebsockets before version 2.2. Building the latest libwebsockets (2.4), mosquitto (1.4.14) and mosquitto-auth-plug fixed it for me.

**Comment by jpmens** [comment] 2018-11-16 16:34
Closing as it appears to be upstream.

**Closed by jpmens** 2018-11-16 16:34 UTC
