### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by andriwarda** [jpmens/mosquitto-auth-plug#203] opened 2017-03-06 03:35 UTC
Hello,
Firstly i want to say thank's for this plugin
I want to know about error:connection refused
I'm trying to publish and subscribe something from terminal and i have result connection refused
`andri@andri-K43SD:~$ mosquitto_pub -t "test" -m "hello" -u "andri" -P "andri"
Error: Connection refused`

I'm trying to use JWT back ends in mosquitto.conf like this 
`# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends jwt
auth_opt_jwt_ip 127.0.0.1
auth_opt_jwt_port 8089
#auth_opt_jwt_hostname example.org
auth_opt_jwt_getuser_uri /auth
auth_opt_jwt_superuser_uri /superuser
auth_opt_jwt_aclcheck_uri /acl`

Running this command 
`/usrl/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`

Can someone give me a suggestion about where to look to find the error?
Thanks in advance

**Comment by bitfreak25** [comment] 2017-03-06 14:48
I couldn't find a type-error. Maybe you can check if you use the right jwt-folder, username and password. Second you can try to check the logfile: **/var/log/mosquitto/mosquitto.log**

I'm not familiar with jwt, but I hope you can find the solution.

**Comment by jpmens** [comment] 2017-03-06 16:08
Connection refused means Mosquitto is not running!

**Comment by andriwarda** [comment] 2017-03-07 04:47
Thank you for fast reply,
When i run `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`
After configure mosquitto.conf its no error message
But when i try to publish topic in other terminal i have error message Connection refused

**Comment by jpmens** [comment] 2017-03-07 07:33
If you get connection refused: see whether Mosquitto is running (`ps`); make sure you have no firewall between client and server, check that Mosquitto's port 1883 is being listened on (`netstat -anp`)

I note that in the configuration you show above, you have no listener; that may be the cause unless you've included other files.

**Comment by andriwarda** [comment] 2017-03-07 07:42
I think my mosquitto.conf didn't run, how i can run mosquitto.conf if with `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf` can't start mosqutto

**Comment by jpmens** [comment] 2017-03-07 07:54
mosquitto.conf is a configuration file; it doesn't "run".
try adding option -v to keep Mosquitto in foreground and check the 
diagnostics you see on the console.

**Comment by andriwarda** [comment] 2017-03-07 08:03
I run `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf` and check mosquitto status with `ps -e`. There's no mosquitto running. And i try to running mosquitto with http back-ends but i have error message `code 400, message Bad HTTP/0.9 request type ('\x10:\x00\x06MQIsdp\x03\xc2\x00<\x00\x17mosqsub/10117-andri-K43\x00')`.

**Comment by bitfreak25** [comment] 2017-03-07 11:49
When you type `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf` into your terminal the program is running until you stop it with Ctrl+C or closing the terminal. It doesn't start a background process!

If the above isn't the problem, you may get information about why the program close itself through the file `/var/log/mosquitto/mosquitto.log` and the output after you start the program with `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`.

**Closed** 2017-04-08 15:30 UTC
