### ISSUE TITLE
Plugin returns MOSQ_ERR_SUCCESS instead of MOSQ_ERR_AUTH

### ISSUE THREAD

**Issue by glynj-bsquare** [jpmens/mosquitto-auth-plug#328] opened 2018-02-20 13:20 UTC
Specific setup - configure a Mongo Db backend, with variables set to look for authorisation PSK
Added extra configuration file containing the following:

```
listener 8883
protocol mqtt
psk_hint MfsHsKyXwW3NYtfDvZYx
auth_plugin /auth_plug/auth-plug.so
### Map to the key names
auth_opt_mongo_database myDb
auth_opt_mongo_user_coll device
auth_opt_mongo_user_username_prop guid
auth_opt_mongo_user_password_prop preSharedKey
auth_opt_psk_database mongo
### Set up server to use
use_identity_as_username true
auth_opt_backends mongo
auth_opt_mongo_uri mongodb://localhost:27017
```

Code configures mosquitto using:  mosquitto_tls_psk_set() with the expected username and PSK, then calls mosquitto_connect().
mosquitto_connect() returns MOSQ_ERR_SUCCESS even if the username does not exist in the MongoDb. Logging from the plugin/mosquitto server combination shows: 

```
1519131059: New connection from 10.150.18.216 on port 8883.
1519131059: |-- psk_key_get(MfsHsKyXwW3NYtfDvZYx, <UserName>) from [mongo] finds PSK: 0
1519131059: OpenSSL Error: error:1408B0DF:SSL routines:ssl3_get_client_key_exchange:psk identity not found
1519131059: Socket error on client <unknown>, disconnecting.
```

The system works fine if the username and PSK match. If they fail to match the code continues as if the connection succeeded, but the connect callback is never called - the connection has failed silently.

**Comment by jpmens** [comment] 2018-11-16 16:29
Does this happen with the mongodb plugin only or also with the other plugins?

**Comment by glynj-bsquare** [comment] 2018-11-19 08:11
We've only tried this with the mongodb plugin as that was our backend for other system data.

**Comment by jpmens** [comment] 2018-11-20 17:53
I cannot reproduce this using Mosquitto's CLI utilities; they behave as I'd expect them to. Furthermore, the authentication plugin definitely returns an authentication denial if we cannot find the correct PSK:

```c
return (psk_found) ? MOSQ_ERR_SUCCESS : MOSQ_DENY_AUTH;
```

I need you to provide an absolute minimal example please in which you demonstrate why you think the code fails.

**Comment by glynj-bsquare** [comment] 2018-11-21 11:38
I apologise that I don't have the bandwidth to replicate our original setup - we have moved to AWS MQTT broker using certificates.
We were using mosquitto version 1.4.15, auth-plugin version 0.1.2, mongo-c-driver version 1.7.0 and mongodb version 2.6.10.
If it still works with on the command line with these versions it's entirely possible that it was the way we used the functions.

**Comment by jpmens** [comment] 2018-11-21 18:13
Thank you for reporting back. I will now close this as not reproducible. Anybody who can is free to re-address.

**Closed by jpmens** 2018-11-21 18:13 UTC
